import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

import AppProvider from "@/context/app";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className + " flex flex-col h-screen"}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
